In [55]:
import numpy as np
from mxnet import nd


# MXNet数据操作

在mxnet中，NDArray是存储和处理数据的主要工具，与numpy功能类似。


打印NDArray数据时，会返回"@cpu(0)"，它表示数组被创建在CPU使用的内存上，0则没有特别的含义，未指定特定的核。


### 1. 创建NDArray

In [56]:
# 使用NDArray创建行向量

x = nd.arange(12)
print(x)


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>


In [57]:
# 通过shape来获取NDArray的形状，通过size来获取NDArray中元素的总数

shape = x.shape
print(shape)

size = x.size
print(size)

(12,)
12


In [58]:
# 通过reshape改变NDArray的形状

X = x.reshape((3, 4))
print(X)

X = x.reshape((3, -1))
print(X)

X = x.reshape((-1, 4))
print(X)

print(x.reshape((5, -1)))
print(x.reshape((-1, 5)))



[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
<NDArray 5x2 @cpu(0)>

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
<NDArray 2x5 @cpu(0)>


In [59]:
# 使用zeros、ones、random来创建指定形状，且元素全为0、1、随机数的矩阵

zeros = nd.zeros((2, 3, 4))
print(zeros)

ones = nd.ones((3, 4))
print(ones)

randoms = nd.random.normal(0, 1, shape=(3, 4))
print(randoms)



[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

[[ 1.6403017  -1.2138013   2.3999705  -0.38509107]
 [-0.98780406  0.9585889  -1.4976466   0.6605163 ]
 [-0.18903568 -0.27302608  0.91815436  2.173063  ]]
<NDArray 3x4 @cpu(0)>


In [60]:
# list、NDArray、numpy的相互转换


# list -> NDArray, numpy

l1 = list(range(12))
print(l1)
nd1 = nd.array(l1)
print(nd1)
np1 = np.array(l1)
print(np1)



# NDArray -> numpy & numpy -> NDArray

np2 = nd1.asnumpy()
print(np2)
nd2 = nd.array(np1)
print(nd2)


# NDArray, numpy -> list。NDArray无法直接转换为list，需要先转为numpy，再转成list

print(nd1.asnumpy().tolist())
print(list(np1), np1.tolist())



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>
[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


### 2. NDArray运算

In [70]:
# 生成两个随机矩阵X和Y，astype将矩阵元素转换为float格式，因为dot运算只支持float格式数据

X = nd.random.randint(0, 2, shape=(3, 4)).astype(float)
print(X)
Y = nd.random.randint(1, 3, shape=(3, 4)).astype(float)
print(Y)

# 加法
print(X + Y)

# 乘法
print(X * Y)

# 使用dot做矩阵乘法
print(nd.dot(X.T, Y))
print(nd.dot(X, Y.T))



[[1. 0. 1. 1.]
 [1. 1. 0. 1.]
 [1. 1. 0. 0.]]
<NDArray 3x4 @cpu(0)>

[[2. 2. 2. 1.]
 [1. 1. 1. 2.]
 [1. 1. 2. 1.]]
<NDArray 3x4 @cpu(0)>

[[3. 2. 3. 2.]
 [2. 2. 1. 3.]
 [2. 2. 2. 1.]]
<NDArray 3x4 @cpu(0)>

[[2. 0. 2. 1.]
 [1. 1. 0. 2.]
 [1. 1. 0. 0.]]
<NDArray 3x4 @cpu(0)>

[[4. 4. 5. 4.]
 [2. 2. 3. 3.]
 [2. 2. 2. 1.]
 [3. 3. 3. 3.]]
<NDArray 4x4 @cpu(0)>

[[5. 4. 4.]
 [5. 4. 3.]
 [4. 2. 2.]]
<NDArray 3x3 @cpu(0)>

[8.]
<NDArray 1 @cpu(0)> 8.0


In [73]:
# 判断矩阵元素是否相等
print(X == Y)

# 对矩阵元素求和，求和得到的依旧是NDArray格式，使用asscalar转换为float格式
print(X.sum(), X.sum().asscalar())



[[0. 0. 0. 1.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]
<NDArray 3x4 @cpu(0)>

[8.]
<NDArray 1 @cpu(0)> 8.0


In [71]:
# 对矩阵做指数运算，也可改写为nd.exp(X)
print(X.exp())

# 对矩阵做sqrt计算，也可改写为nd.sqrt(X)
print(Y.sqrt())

# 对矩阵做log计算，也可改写为nd.log(X)
print(Y.log())



[[2.71828183 1.         2.71828183 2.71828183]
 [2.71828183 2.71828183 1.         2.71828183]
 [2.71828183 2.71828183 1.         1.        ]]
<NDArray 3x4 @cpu(0)>

[[1.41421356 1.41421356 1.41421356 1.        ]
 [1.         1.         1.         1.41421356]
 [1.         1.         1.41421356 1.        ]]
<NDArray 3x4 @cpu(0)>

[[0.69314718 0.69314718 0.69314718 0.        ]
 [0.         0.         0.         0.69314718]
 [0.         0.         0.69314718 0.        ]]
<NDArray 3x4 @cpu(0)>


In [72]:
# 将两个矩阵联结（concatenate）到一个矩阵，dim=0在行上添加，dim=1在列上添加

new_nd1 = nd.concat(X, Y, dim=0)
print(new_nd1)

new_nd2 = nd.concat(X, Y, dim=1)
print(new_nd2)



[[1. 0. 1. 1.]
 [1. 1. 0. 1.]
 [1. 1. 0. 0.]
 [2. 2. 2. 1.]
 [1. 1. 1. 2.]
 [1. 1. 2. 1.]]
<NDArray 6x4 @cpu(0)>

[[1. 0. 1. 1. 2. 2. 2. 1.]
 [1. 1. 0. 1. 1. 1. 1. 2.]
 [1. 1. 0. 0. 1. 1. 2. 1.]]
<NDArray 3x8 @cpu(0)>


### 3. NDArray广播与索引


In [78]:
# 广播

# 随机生成不同shape的X和Y，X为M行1列，Y为1行N列
m, n = 3, 2
X = nd.random.randint(0, 2, shape=(m, 1))
print(X)
Y = nd.random.randint(1, 3 ,shape=(1, n))
print(Y)

# X和Y的运算，会进行广播
print(X + Y)
print(X * Y)



[[0]
 [0]
 [1]]
<NDArray 3x1 @cpu(0)>

[[2 1]]
<NDArray 1x2 @cpu(0)>

[[2 1]
 [2 1]
 [3 2]]
<NDArray 3x2 @cpu(0)>

[[0 0]
 [0 0]
 [2 1]]
<NDArray 3x2 @cpu(0)>


In [81]:
# NDArray索引

X = nd.random.randint(0, 2, shape=(3, 4))
print(X)

# 行索引
print(X[1])

# 列索引
print(X[:, 1])

# 元素索引
print(X[1, 1])


[[0 1 1 0]
 [1 0 1 1]
 [1 1 0 0]]
<NDArray 3x4 @cpu(0)>

[1 0 1 1]
<NDArray 4 @cpu(0)>

[1 0 1]
<NDArray 3 @cpu(0)>

[0]
<NDArray 1 @cpu(0)>
